name: detective_game
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  flame: ^0.22.0
  auto_size_text: ^2.1.0
  shared_preferences: ^0.5.7+3
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
     - assets/images/
     - assets/images/characters/avatars/
     - assets/images/configuration_set/

     # Main Thread Audio + Graphics
     - assets/images/locations/main_thread/01/
     - assets/images/locations/main_thread/02/
     - assets/images/locations/main_thread/03/
     - assets/images/locations/main_thread/04/
     - assets/images/locations/main_thread/05/
     - assets/images/locations/main_thread/06/
     - assets/images/locations/main_thread/07/
     - assets/images/locations/main_thread/08/
     - assets/images/locations/main_thread/09/
     - assets/images/locations/main_thread/10/
     - assets/images/locations/main_thread/11/
     - assets/images/locations/main_thread/12/
     - assets/images/locations/main_thread/13/
     - assets/images/locations/main_thread/14/
     - assets/images/locations/main_thread/15/
     - assets/audio/dialogues/main_thread/01/
     - assets/audio/dialogues/main_thread/02/
     - assets/audio/dialogues/main_thread/03/
     - assets/audio/dialogues/main_thread/04/
     - assets/audio/dialogues/main_thread/05/
     - assets/audio/dialogues/main_thread/06/
     - assets/audio/dialogues/main_thread/07/
     - assets/audio/dialogues/main_thread/08/
     - assets/audio/dialogues/main_thread/09/
     - assets/audio/dialogues/main_thread/10/
     - assets/audio/dialogues/main_thread/11/
     - assets/audio/dialogues/main_thread/12/
     - assets/audio/dialogues/main_thread/13/
     - assets/audio/dialogues/main_thread/14/
     - assets/audio/dialogues/main_thread/15/     
    
     # Daniel Thread Audio + Graphics
     - assets/images/locations/daniel_thread/01/
     - assets/images/locations/daniel_thread/02/
     - assets/images/locations/daniel_thread/03/
     - assets/images/locations/daniel_thread/04/
     - assets/audio/dialogues/daniel_thread/01/
     - assets/audio/dialogues/daniel_thread/02/
     - assets/audio/dialogues/daniel_thread/03/
     - assets/audio/dialogues/daniel_thread/04/

     # Jeff Thread Audio + Graphics
     - assets/images/locations/jeff_thread/01/
     - assets/images/locations/jeff_thread/02/
     - assets/images/locations/jeff_thread/03/
     - assets/images/locations/jeff_thread/04/
     - assets/images/locations/jeff_thread/05/
     - assets/audio/dialogues/jeff_thread/01/
     - assets/audio/dialogues/jeff_thread/02/
     - assets/audio/dialogues/jeff_thread/03/
     - assets/audio/dialogues/jeff_thread/04/
     - assets/audio/dialogues/jeff_thread/05/

     # Kate Thread Audio + Graphics
     - assets/images/locations/kate_thread/01/
     - assets/images/locations/kate_thread/02/
     - assets/images/locations/kate_thread/03/
     - assets/images/locations/kate_thread/04/
     - assets/images/locations/kate_thread/05/
     - assets/images/locations/kate_thread/06/
     - assets/images/locations/kate_thread/07/
     - assets/images/locations/kate_thread/08/
     - assets/images/locations/kate_thread/09/
     - assets/audio/dialogues/kate_thread/01/
     - assets/audio/dialogues/kate_thread/02/
     - assets/audio/dialogues/kate_thread/03/
     - assets/audio/dialogues/kate_thread/04/
     - assets/audio/dialogues/kate_thread/05/
     - assets/audio/dialogues/kate_thread/06/
     - assets/audio/dialogues/kate_thread/07/
     - assets/audio/dialogues/kate_thread/08/
     - assets/audio/dialogues/kate_thread/09/
     
     # Luca Thread Audio + Graphics
     - assets/images/locations/luca_thread/01/
     - assets/audio/dialogues/luca_thread/01/

     # Mike Thread Audio + Graphics    
     - assets/images/locations/mike_thread/01/
     - assets/images/locations/mike_thread/02/
     - assets/images/locations/mike_thread/03/
     - assets/images/locations/mike_thread/04/
     - assets/images/locations/mike_thread/05/
     - assets/images/locations/mike_thread/06/
     - assets/images/locations/mike_thread/07/
     - assets/images/locations/mike_thread/08/
     - assets/images/locations/mike_thread/09/
     - assets/audio/dialogues/mike_thread/01/
     - assets/audio/dialogues/mike_thread/02/
     - assets/audio/dialogues/mike_thread/03/
     - assets/audio/dialogues/mike_thread/04/
     - assets/audio/dialogues/mike_thread/05/
     - assets/audio/dialogues/mike_thread/06/
     - assets/audio/dialogues/mike_thread/07/
     - assets/audio/dialogues/mike_thread/08/
     - assets/audio/dialogues/mike_thread/09/

  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand/QuickSand-Bold.ttf
        - asset: assets/fonts/Quicksand/QuickSand-Light.ttf
        - asset: assets/fonts/Quicksand/QuickSand-Medium.ttf
        - asset: assets/fonts/Quicksand/QuickSand-Regular.ttf
